//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.CarDelivery {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fullPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string markField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int motorValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiptTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customPrice {
            get {
                return this.customPriceField;
            }
            set {
                if ((this.customPriceField.Equals(value) != true)) {
                    this.customPriceField = value;
                    this.RaisePropertyChanged("customPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fullPrice {
            get {
                return this.fullPriceField;
            }
            set {
                if ((this.fullPriceField.Equals(value) != true)) {
                    this.fullPriceField = value;
                    this.RaisePropertyChanged("fullPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mark {
            get {
                return this.markField;
            }
            set {
                if ((object.ReferenceEquals(this.markField, value) != true)) {
                    this.markField = value;
                    this.RaisePropertyChanged("mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int motorValue {
            get {
                return this.motorValueField;
            }
            set {
                if ((this.motorValueField.Equals(value) != true)) {
                    this.motorValueField = value;
                    this.RaisePropertyChanged("motorValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiptTime {
            get {
                return this.receiptTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.receiptTimeField, value) != true)) {
                    this.receiptTimeField = value;
                    this.RaisePropertyChanged("receiptTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnTime {
            get {
                return this.returnTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.returnTimeField, value) != true)) {
                    this.returnTimeField = value;
                    this.RaisePropertyChanged("returnTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarDelivery.ICarDelivery")]
    public interface ICarDelivery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/TestConnection", ReplyAction="http://tempuri.org/ICarDelivery/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/TestConnection", ReplyAction="http://tempuri.org/ICarDelivery/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/AddData", ReplyAction="http://tempuri.org/ICarDelivery/AddDataResponse")]
        WebClient.CarDelivery.Order AddData(WebClient.CarDelivery.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/AddData", ReplyAction="http://tempuri.org/ICarDelivery/AddDataResponse")]
        System.Threading.Tasks.Task<WebClient.CarDelivery.Order> AddDataAsync(WebClient.CarDelivery.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintOrder", ReplyAction="http://tempuri.org/ICarDelivery/PrintOrderResponse")]
        WebClient.CarDelivery.Order PrintOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintOrder", ReplyAction="http://tempuri.org/ICarDelivery/PrintOrderResponse")]
        System.Threading.Tasks.Task<WebClient.CarDelivery.Order> PrintOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintAllOrders", ReplyAction="http://tempuri.org/ICarDelivery/PrintAllOrdersResponse")]
        WebClient.CarDelivery.Order[] PrintAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintAllOrders", ReplyAction="http://tempuri.org/ICarDelivery/PrintAllOrdersResponse")]
        System.Threading.Tasks.Task<WebClient.CarDelivery.Order[]> PrintAllOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarDeliveryChannel : WebClient.CarDelivery.ICarDelivery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarDeliveryClient : System.ServiceModel.ClientBase<WebClient.CarDelivery.ICarDelivery>, WebClient.CarDelivery.ICarDelivery {
        
        public CarDeliveryClient() {
        }
        
        public CarDeliveryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarDeliveryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDeliveryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDeliveryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public WebClient.CarDelivery.Order AddData(WebClient.CarDelivery.Order order) {
            return base.Channel.AddData(order);
        }
        
        public System.Threading.Tasks.Task<WebClient.CarDelivery.Order> AddDataAsync(WebClient.CarDelivery.Order order) {
            return base.Channel.AddDataAsync(order);
        }
        
        public WebClient.CarDelivery.Order PrintOrder(int id) {
            return base.Channel.PrintOrder(id);
        }
        
        public System.Threading.Tasks.Task<WebClient.CarDelivery.Order> PrintOrderAsync(int id) {
            return base.Channel.PrintOrderAsync(id);
        }
        
        public WebClient.CarDelivery.Order[] PrintAllOrders() {
            return base.Channel.PrintAllOrders();
        }
        
        public System.Threading.Tasks.Task<WebClient.CarDelivery.Order[]> PrintAllOrdersAsync() {
            return base.Channel.PrintAllOrdersAsync();
        }
    }
}
