//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCli.CarReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarReference.ICarDelivery")]
    public interface ICarDelivery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/TestConnection", ReplyAction="http://tempuri.org/ICarDelivery/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/TestConnection", ReplyAction="http://tempuri.org/ICarDelivery/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/AddData", ReplyAction="http://tempuri.org/ICarDelivery/AddDataResponse")]
        string AddData(string mark, int age, int price, int motor_value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/AddData", ReplyAction="http://tempuri.org/ICarDelivery/AddDataResponse")]
        System.Threading.Tasks.Task<string> AddDataAsync(string mark, int age, int price, int motor_value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintOutput", ReplyAction="http://tempuri.org/ICarDelivery/PrintOutputResponse")]
        string PrintOutput(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDelivery/PrintOutput", ReplyAction="http://tempuri.org/ICarDelivery/PrintOutputResponse")]
        System.Threading.Tasks.Task<string> PrintOutputAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarDeliveryChannel : ConsoleCli.CarReference.ICarDelivery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarDeliveryClient : System.ServiceModel.ClientBase<ConsoleCli.CarReference.ICarDelivery>, ConsoleCli.CarReference.ICarDelivery {
        
        public CarDeliveryClient() {
        }
        
        public CarDeliveryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarDeliveryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDeliveryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDeliveryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public string AddData(string mark, int age, int price, int motor_value) {
            return base.Channel.AddData(mark, age, price, motor_value);
        }
        
        public System.Threading.Tasks.Task<string> AddDataAsync(string mark, int age, int price, int motor_value) {
            return base.Channel.AddDataAsync(mark, age, price, motor_value);
        }
        
        public string PrintOutput(string id) {
            return base.Channel.PrintOutput(id);
        }
        
        public System.Threading.Tasks.Task<string> PrintOutputAsync(string id) {
            return base.Channel.PrintOutputAsync(id);
        }
    }
}
